---
- name: Add repo file
  template: src=nginx_centos.repo.j2 dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644

- name: Add repo key
  get_url: url=http://nginx.org/keys/nginx_signing.key dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx sha256sum=dd4da5dc599ef9e7a7ac20a87275024b4923a917a306ab5d53fa77871220ecda force=yes

- name: Add repo key
  file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx owner=root group=root mode=0644

- name: Add repo key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx

- name: Install Nginx
  yum: name=nginx enablerepo=nginx state=present
